enum SidcAmplifier {
    UNKNOWN = 0,

    TEAM_OR_CREW = 11,
    SQUAD = 12,
    SECTION = 13,
    PLATOON_OR_DETACHMENT = 14,
    COMPANY_OR_BATTERY_OR_TROOP = 15,
    BATTALION_OR_SQUADRON = 16,
    REGIMENT_OR_GROUP = 17,
    BRIGADE = 18,

    DIVISION = 21,
    CORPS_OR_MARINE_EXPEDITIONARY_FORCE = 22,
    ARMY = 23,
    ARMY_GROUP_OR_FRONT = 24,
    REGION_OR_THEATRE = 25,
    COMMAND = 26,

    STANDARD_MOBILITY_OR_ON_ROAD_MOBILITY = 31,
    HIGH_MOBILITY_OR_OFF_ROAD_MOBILITY = 32,
    TRACKED = 33,
    WHEELED_AND_TRACKED_COMBINATION = 34,
    TOWED = 35,
    RAIL = 36,
    PACK_ANIMALS = 37,

    OVER_SNOW_PRIME_MOVER = 41,
    SLED = 42,

    BARGE = 51,
    AMPHIBIOUS = 52,

    SHORT_TOWED_ARRAY = 61,
    LONG_TOWED_ARRAY = 62,

    LEADER_INDIVIDUAL = 71,
}

export default SidcAmplifier;
