enum SidcContext {
    REALITY = 0,
    EXERCISE = 1,
    SIMULATION = 2,
    RESTRICTED_TARGET = 3,
    NO_STRIKE_ENTITY = 4,
    RESTRICTED_TARGET_EXERCISE = 5,
    NO_STRIKE_ENTITY_EXERCISE = 6,
    RESTRICTED_TARGET_SIMULATION1 = 7,
    NO_STRIKE_ENTITY_SIMULATION = 8,
}

export default SidcContext;
