enum SidcTaskForce {
    NOT_APPLICABLE = 0,
    FEINT_OR_DUMMY = 1,
    HEADQUARTERS = 2,
    FEINT_OR_DUMMY_HEADQUARTERS = 3,
    TASK_FORCE = 4,
    FEINT_OR_DUMMY_TASK_FORCE = 5,
    TASK_FORCE_HEADQUARTERS = 6,
    FEINT_OR_DUMMY_TASK_FORCE_HEADQUARTERS = 7,
}

export default SidcTaskForce;
